### ISSUE TITLE
DOM "change" event not fired on inputs

### ISSUE THREAD

**Issue by kensnyder** [angular-ui/ui-mask#53]
**Minimal test case** [here](http://plnkr.co/edit/QuGxfrIWGCpcw33Zy0G5?p=preview)

**To reproduce** type in one digit then tab out

**Expected behavior:** events on regular input fire `keydown`, `input`, `keyup`, **`change`**, `blur`
**Actual behavior:** events on ui-mask input fire `keydown`, `input`, `keyup`, `blur`

Because `iElement.val(maskedValue)` is called in several places, the `change` event never fires. Browsers only fire `change` events in response to user input, not in response to JavaScript setting the input's `value` property.

**Possible fix:** Observe the blur event and manually dispatch a `change` event when the new value is different. In that case `blur` will fire after `change` in most situations, but it is better than not firing `change` at all.

I'm not familiar with the code enough to be able to create a patch. A cursory glance of the code indicates that the event should probably be fired from inside the `blurHandler` function but it isn't obvious how to tell if the value really changed since focusing.

The use case is an autosave directive that observes `change` events on a parent div to catch any changes to form elements inside the div; in response to the change, the directive sends a PATCH request with the new value. The directive uses delegation so that events are captured regardless of inputs being dynamically added or removed. The directive could observe `blur` to catch changes, but `blur` events do not bubble up and the similar `focusout` event that does bubble is not supported in Firefox.

**Comment by marbletravis** [comment]
@kensnyder I had some time to look at this (needed something easy and productive to do)

Check out the plunkr demo here: http://plnkr.co/edit/ux2uj6V4vkDXnZZyQpsU?p=preview

I will create a pull request, I think I agree that it should be fixed, but I will let others chime in with their opinions as well.

**Comment by kensnyder** [comment]
@marbletravis I don't see your patch working on the plunkr. The HTML is trying to load `ui-mask-patched.js` but there is only a file called `ui-mask-patched` with no extension. I changed the filename to have a `js` extension and ui-mask directive loaded but still no onchange fired. Is that what you're seeing?

My coworker suggested creating a second `ui.mask` directive that runs alongside the first. All it would do is listen for blur and then fire a synthetic `change` event. I'm going to draft that up and make a plunkr.

**Comment by marbletravis** [comment]
@kensnyder can you try the plunkr again, I forgot to freeze it.

Travis

**Comment by kensnyder** [comment]
@marbletravis Does the frozen one have a new URL? I'm still seeing the same thing.

Here is my gist for a [second directive](https://gist.github.com/kensnyder/c145b25e9147b57feec8) I will add to a new plunkr demo when I have a chance.

**Comment by marbletravis** [comment]
Try the plunkr again, sorry about that. I would think it would be best if your changes were in the main repo (assuming others felt change should be called).

http://plnkr.co/edit/ux2uj6V4vkDXnZZyQpsU?p=preview

I borrowed your trigger event logic for the plunkr, which better handles the case where you are not using jquery to listen for the events.

**Comment by PowerKiKi** [comment]
Closed via #54
